//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPComm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfgAccountEnabled {
            get {
                return ((bool)(this["cfgAccountEnabled"]));
            }
            set {
                this["cfgAccountEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfgAccountIndex {
            get {
                return ((int)(this["cfgAccountIndex"]));
            }
            set {
                this["cfgAccountIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1005")]
        public string cfgAccountName {
            get {
                return ((string)(this["cfgAccountName"]));
            }
            set {
                this["cfgAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.10.111")]
        public string cfgAccountAddress {
            get {
                return ((string)(this["cfgAccountAddress"]));
            }
            set {
                this["cfgAccountAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1005")]
        public string cfgAccountID {
            get {
                return ((string)(this["cfgAccountID"]));
            }
            set {
                this["cfgAccountID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1005")]
        public string cfgAccountUsername {
            get {
                return ((string)(this["cfgAccountUsername"]));
            }
            set {
                this["cfgAccountUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string cfgAccountPassword {
            get {
                return ((string)(this["cfgAccountPassword"]));
            }
            set {
                this["cfgAccountPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1005")]
        public string cfgAccountDisplayName {
            get {
                return ((string)(this["cfgAccountDisplayName"]));
            }
            set {
                this["cfgAccountDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.10.10.111")]
        public string cfgAccountDomain {
            get {
                return ((string)(this["cfgAccountDomain"]));
            }
            set {
                this["cfgAccountDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfgAccountState {
            get {
                return ((int)(this["cfgAccountState"]));
            }
            set {
                this["cfgAccountState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgAccountProxyAddress {
            get {
                return ((string)(this["cfgAccountProxyAddress"]));
            }
            set {
                this["cfgAccountProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfgAccountTransport {
            get {
                return ((int)(this["cfgAccountTransport"]));
            }
            set {
                this["cfgAccountTransport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgCFUFlag {
            get {
                return ((bool)(this["cfgCFUFlag"]));
            }
            set {
                this["cfgCFUFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFUNumber {
            get {
                return ((string)(this["cfgCFUNumber"]));
            }
            set {
                this["cfgCFUNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgCFNRFlag {
            get {
                return ((bool)(this["cfgCFNRFlag"]));
            }
            set {
                this["cfgCFNRFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFNRNumber {
            get {
                return ((string)(this["cfgCFNRNumber"]));
            }
            set {
                this["cfgCFNRNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgDNDFlag {
            get {
                return ((bool)(this["cfgDNDFlag"]));
            }
            set {
                this["cfgDNDFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgAAFlag {
            get {
                return ((bool)(this["cfgAAFlag"]));
            }
            set {
                this["cfgAAFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgCFBFlag {
            get {
                return ((bool)(this["cfgCFBFlag"]));
            }
            set {
                this["cfgCFBFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgCFBNumber {
            get {
                return ((string)(this["cfgCFBNumber"]));
            }
            set {
                this["cfgCFBNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5060")]
        public int cfgSipPort {
            get {
                return ((int)(this["cfgSipPort"]));
            }
            set {
                this["cfgSipPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cfgSipPublishEnabled {
            get {
                return ((bool)(this["cfgSipPublishEnabled"]));
            }
            set {
                this["cfgSipPublishEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgStunServerAddress {
            get {
                return ((string)(this["cfgStunServerAddress"]));
            }
            set {
                this["cfgStunServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfgDtmfMode {
            get {
                return ((int)(this["cfgDtmfMode"]));
            }
            set {
                this["cfgDtmfMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600")]
        public int cfgRegistrationTimeout {
            get {
                return ((int)(this["cfgRegistrationTimeout"]));
            }
            set {
                this["cfgRegistrationTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int cfgECTail {
            get {
                return ((int)(this["cfgECTail"]));
            }
            set {
                this["cfgECTail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgVAD {
            get {
                return ((bool)(this["cfgVAD"]));
            }
            set {
                this["cfgVAD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgNameServer {
            get {
                return ((string)(this["cfgNameServer"]));
            }
            set {
                this["cfgNameServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int cfgAccountDefault {
            get {
                return ((int)(this["cfgAccountDefault"]));
            }
            set {
                this["cfgAccountDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection cfgCodecList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cfgCodecList"]));
            }
            set {
                this["cfgCodecList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoRegister {
            get {
                return ((bool)(this["AutoRegister"]));
            }
            set {
                this["AutoRegister"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cfgUpdgradeSettings {
            get {
                return ((bool)(this["cfgUpdgradeSettings"]));
            }
            set {
                this["cfgUpdgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int cfgAATimeout {
            get {
                return ((int)(this["cfgAATimeout"]));
            }
            set {
                this["cfgAATimeout"] = value;
            }
        }
    }
}
